<div class="row m0 sidebar sidebar-category" style="padding-bottom:15px">
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-6903153918119900",
    enable_page_level_ads: true
  });
</script>
	<h4 class="sidebar-title">Kategori</h4>
	<ul class="nav nav-pills nav-stacked">
		<?php echo $this->category($this->slug, TRUE); ?>
	</ul>
</div>