<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
                <span class="icon-bar"></span>
            	<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>">Madaniyah</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<!-- <li data-route="core_index_index"><a href="<?php //echo $this->baseUrl(); ?>"><span class="glyphicon glyphicon-home"></span> Home</a></li>
				<li data-route="news_article_add"><a href="<?php //echo $this->url([],'news_article_add'); ?>"><span class="glyphicon glyphicon-tasks"></span> Post</a></li>
				<li data-route=""><a href=""><span class="glyphicon glyphicon-info-sign"></span> About</a></li> -->
			</ul>
			<div class="col-sm-3 col-md-3">
				<form class="navbar-form" role="search" action="<?php echo $this->APP_URL; ?>/search" method="GET" id="search-form">
					<div class="input-group">
			            <input type="text" class="form-control" placeholder="Search ..." name="q" value="<?php echo $this->layout()->searchQuery; ?>" style="padding:6px 6px;">
			            <div class="input-group-btn">
			                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
			            </div>
					</div>
				</form>
			</div>
			<ul class="nav navbar-nav navbar-right">
				<?php if ($this->isLoggedIn) : ?>
				<li>
					<a style="padding: 10px 0 10px 0;" href="#">
						<img style="width: 30px; height: 30px;" src="https://lh4.googleusercontent.com/-2Sjl0d4Cnvk/AAAAAAAAAAI/AAAAAAAAAFQ/ohQIz_Stz5k/photo.jpg?s=30">
					</a>
				</li>
				<li class="divider-vertical"></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<?php echo $this->getIdentity->user_name; ?><b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><a href="<?php echo $this->url(array('username'=>$this->getIdentity->user_name),'core_auth_profile') ?>"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
						<li><a href="#"><span class="glyphicon glyphicon-cog"></span> Settings</a></li>
						<li class="divider"></li>
						<li>
							<?php
							$sReturn = "http://".$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'];
							$sReturn = base64_encode($sReturn);
							?>
							<a href="<?php echo $this->url(array('returnUrl' => $sReturn),'core_auth_logout'); ?>">
								<span class="glyphicon glyphicon-off"></span> Logout
							</a>
						</li>
					</ul>
				</li>
				<?php else : ?>
				<li id="nav-register-btn" data-route="core_auth_signup"><a href="<?php echo $this->url([],'core_auth_signup'); ?>">Register</a></li>
				<li id="nav-login-btn" data-route="core_auth_login"><a href="<?php echo $this->url([],'core_auth_login'); ?>"><i class="glyphicon glyphicon-log-in"></i> Login</a></li>
				<?php endif; ?>
			</ul>
		</div>
	</div>
</nav>