<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=<?php echo $this->CHARSET; ?>" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->APP_STATIC_SERVER; ?>/skins/<?php echo $this->APP_TEMPLATE; ?>/<?php echo $this->APP_SKIN; ?>/img/w.ico" />
	
	<!--Fonts-->
    <link href='https://fonts.googleapis.com/css?family=Karla:400,400italic,700italic,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lora:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
    
	<?php 
	$this->headLink()
		->prependStylesheet($this->APP_STATIC_SERVER . '/skins/' . $this->APP_TEMPLATE . '/' . $this->APP_SKIN . '/css/style.css')
		->prependStylesheet($this->APP_STATIC_SERVER . '/skins/' . $this->APP_TEMPLATE . '/' . $this->APP_SKIN . '/css/font-awesome.min.css')
		->prependStylesheet($this->APP_STATIC_SERVER . '/skins/' . $this->APP_TEMPLATE . '/' . $this->APP_SKIN . '/css/bootstrap-theme.min.css')
		->prependStylesheet($this->APP_STATIC_SERVER . '/skins/' . $this->APP_TEMPLATE . '/' . $this->APP_SKIN . '/css/bootstrap.min.css');
	
	$this->headScript()
		->prependFile($this->APP_STATIC_SERVER . '/skins/' . $this->APP_TEMPLATE . '/' . $this->APP_SKIN . '/js/bootstrap.min.js')
		->prependFile($this->APP_STATIC_SERVER . '/js/jquery/jquery.min.js');
	?>
	
	<?php
    /**
     * Compress CSS and JS if it is enabled
     */ 
    echo $this->compressor('css');
    echo $this->compressor('js');
    ?>
	
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="<?php echo $this->APP_STATIC_SERVER; ?>/skins/<?php echo $this->APP_TEMPLATE; ?>/<?php echo $this->APP_SKIN; ?>/js/html5shiv.min.js"></script>
      <script src="<?php echo $this->APP_STATIC_SERVER; ?>/skins/<?php echo $this->APP_TEMPLATE; ?>/<?php echo $this->APP_SKIN; ?>/js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<?php echo $this->render('_navigation.phtml'); ?>
<div class="container">
	<?php echo $this->flashMessenger(); ?>
	<?php echo $this->layoutLoader(); ?>
	<hr>
	<footer>
		<div class=container>
			<ul class="list-inline">
				<li><a href="<?php echo $this->APP_URL; ?>/sitemap">Site Map</a></li> 
				<li><a href="<?php echo $this->APP_URL; ?>/privacy">Privacy Policy</a></li>
				<li><a href="<?php echo $this->APP_URL; ?>/terms">Terms of Service</a></li>
				<li><a href="<?php echo $this->APP_URL; ?>/about">About</a></li>
				<li><a href="<?php echo $this->APP_URL; ?>/contact">Contact</a></li>
			</ul>
    		<p>&copy; 2008 - <?php echo date('Y') ?> madaniyah.</p>
    	</div>
	</footer>
</div>
<a id="back-to-top" href="#" class="btn btn-default btn-circle back-to-top" role="button" title="Click to return on the top page" data-toggle="tooltip" data-placement="left"><span class="glyphicon glyphicon-chevron-up"></span></a>
<?php $this->headScript()->captureStart(); ?>
$(function() {
	<?php if (Zend_Controller_Front::getInstance()->getRouter()->getCurrentRouteName()=='news_article_edit') : ?>
	$("#category").select2();
	$("#category").select2('val',[<?php echo $this->layout()->selectedCategory; ?>]);	
	<?php endif; ?>
	<?php if (Zend_Controller_Front::getInstance()->getRouter()->getCurrentRouteName()=='news_article_add') : ?>
	$('#addPostForm').validate({
		rules: {
			title: {
				required:true,
				remote:{
					url:"<?php echo $this->url([],'news_article_checkslug'); ?>",
					type:"post"
				}
			},
			price: {
				number:true
			},
			terms: "required"
		},
		messages: {
			terms: " "
		},
		highlight: function(element) {
            $(element).closest('.form-group').addClass('has-error');
        },
        unhighlight: function(element) {
            $(element).closest('.form-group').removeClass('has-error');
        },
        errorElement: 'span',
        errorClass: 'help-block',
        errorPlacement: function(error, element) {
        	if(element.is(':checkbox')) {
        		error.appendTo(element.next());
        	}
            else if(element.parent('.input-group').length) {
                error.insertAfter(element.parent());
            } else {
                error.insertAfter(element);
            }
        }
	});
	
	$('#<?php echo $this->uploadElementId; ?>').uploadifive({
		'formData' : {
			mod: "<?php echo $this->module; ?>"
			<?php if (isset($this->options['thumbnails'])) : ?>, 
			thumbnails: "<?php echo $this->options['thumbnails']; ?>"
			<?php endif; ?>
		},
		//'queueID' : 'queue',
		'fileType' : ['image/png','image/jpg','image/jpeg','image/gif'],
		'queueSizeLimit' : '<?php echo $this->options['queueSizeLimit']; ?>',
		'fileSizeLimit': '<?php echo $this->options['fileSizeLimit']; ?>',
		'removeCompleted' : <?php if (isset($this->options['removeCompleted']) && ($this->options['removeCompleted'] == true)) : ?>true<?php else : ?>false<?php endif; ?>,
		'auto': <?php if (isset($this->options['auto']) && ($this->options['auto'] == true)) : ?>true<?php else : ?>false<?php endif; ?>,
		'multi': <?php if (isset($this->options['multi']) && ($this->options['multi'] == true)) : ?>true<?php else : ?>false<?php endif; ?>,
		'uploadScript' : '<?php echo $this->url([],'upload_file_upload'); ?>',
		<?php if (isset($this->handlers['onError'])) : ?>
		'onError': function(errorType) {
			
			<?php echo $this->handlers['onError']; ?>(errorType);
			 
		}, 
		<?php endif; ?>
		<?php if (isset($this->handlers['onCancel'])) : ?>
		'onCancel': function() {
			 
			<?php echo $this->handlers['onCancel']; ?>();
			 
		}, 
		<?php endif; ?>
		<?php if (isset($this->handlers['onClearQueue'])) : ?>
		'onClearQueue': function(queue) {
			
			<?php echo $this->handlers['onClearQueue']; ?>(queue);
			 
		},
		<?php endif; ?>
		<?php if (isset($this->handlers['onProgress'])) : ?>
		onProgress: function(file, e) {
			
			<?php echo $this->handlers['onProgress']; ?>(file, e);
			 
		},
		<?php endif; ?>
		<?php if (isset($this->handlers['onUploadComplete'])) : ?>
		'onUploadComplete' : function(file, data) { 
			
			<?php echo $this->handlers['onUploadComplete']; ?>(file, data);
			 
		},
		<?php endif; ?>
		<?php if ($this->options['queueSizeLimit'] > 0) : ?>
		'onSelect' : function(queue) {
			var i = $(".img-thumbnail").size(),
				x = '<?php echo $this->options['queueSizeLimit'] - 1; ?>';
				
            if (i > x)
            {
            	$('#<?php echo $this->uploadElementId; ?>').uploadifive('clearQueue');
            	alert('The maximum number of items has been reached(7)');
            }
        },
        <?php endif; ?>
		'onFallback': function(){
     		alert('HTML5 is not supported in this browser. Please upgrade your browser');
    	}
	
	});
	
	$('#datetimepicker1').datetimepicker({
		pick12HourFormat: false,
		sideBySide: true
    });
	$('#datetimepicker2').datetimepicker({
		pick12HourFormat: false,
		sideBySide: true
    });
	$('#datetimepicker3').datetimepicker({
		pick12HourFormat: false,
		sideBySide: true
    });
    
    $('#type').on('change',function(){
    	var id = $(this).val();
    	if (id == 'clinic'){
			$('#addquestion').slideDown();
			$('#addcategory').slideDown();
			
			$('#addcopri').slideUp();
			$('#addcontent').slideUp();
		}
		else if ($.inArray(id,['author','source'])!==-1){
			$('#addcategory').slideUp();
			$('#addcopri').slideUp();
			$('#addquestion').slideUp();
			
			$('#addcontent').slideDown();
		}
		else
		{
			$('#addcategory').slideDown();
			$('#addcopri').slideDown();
			$('#addcontent').slideDown();
			
			$('#addquestion').slideUp();
		}
		
		return false;
    });
    
    $("#category").select2();	
	<?php endif; ?>
	
	<?php if (Zend_Controller_Front::getInstance()->getRouter()->getCurrentRouteName()=='news_article_details') : ?>
	$("#share").jsSocials({
		showLabel: false,
		showCount: "inside",
		shareIn: "popup",
		shares: ["email", "twitter", "facebook", "googleplus", "linkedin", "pinterest", "stumbleupon", "whatsapp"]
	});
	
	<?php endif; ?>
	
	$(window).scroll(function () {
		if ($(this).scrollTop() > 50) {
			$('#back-to-top').fadeIn();
		}
		else
		{
			$('#back-to-top').fadeOut();
		}
	});
    		
  	$('#back-to-top').click(function () {
		$('#back-to-top').tooltip('hide');
		$('body,html').animate({
           	scrollTop: 0
       	}, 800);
       	return false;
   	});
    		
   	$('#back-to-top').tooltip('show');
   	
   	
	<?php if (Zend_Controller_Front::getInstance()->getRouter()->getCurrentRouteName()=='core_index_contactus') : ?>
	var cDestination,
       	currentLat,
       	currentLong,
       	markerCurrent;
	function arahjalan(destination,position)
    {
       	if(typeof destination!="undefined") cDestination=destination;  
       	if(typeof position!="undefined") 
       	{
       		currentLat=position.coords.latitude;
       		currentLong=position.coords.longitude;
       	}
       	if(typeof currentLat!="undefined" && typeof currentLong!="undefined")
       	{
       		var strURL="http://maps.google.com/";
       		strURL+="maps?saddr="+currentLat+","+currentLong+"&daddr="+cDestination;
       		window.open(strURL,'_blank'); 
       	}
       	else
       	{
       		$.fancybox( {href : '#dialogContent', title : '',type:'inline',afterShow:initSearchAddress} );
       	}
    }
       	
	<?php endif; ?>
   	
	<?php if (Zend_Controller_Front::getInstance()->getRouter()->getCurrentRouteName()=='core_index_contact') : ?>
	$('input').iCheck({
		checkboxClass: 'icheckbox_square-blue',
		increaseArea: '20%' // optional
	});
	<?php endif; ?>
	
});

<?php if (Zend_Controller_Front::getInstance()->getRouter()->getCurrentRouteName()=='news_article_add') : ?>
function onUploadComplete(fileObj,response)
{
	var images = $.evalJSON(response);
	console.info(images);
	var presentImage = $('<img/>');
	$(presentImage).attr('src', images.thumbnail.url)
		.attr('width', '100').attr('height', '100')
		.attr('style', 'cursor: pointer')
		.click(function() {
			$('#uploadFiles').uploadifive('cancel', $.post('<?php echo $this->url([],'upload-file-delete'); ?>',{img:$.toJSON(images)}));
			$(this).closest('li').remove();			
		});
	var select = $('<select/>');
	$(select).attr('width', '100');
	$('<option/>').attr('value', '').html('---').appendTo(select);

	for (var thumb in images) {
		$('<option/>').attr('value', images[thumb].url).html(images[thumb].size).appendTo(select);
	}	
	$('<option/>').attr('value', 'addattribute').attr('data-options',images.original.url.replace(/^.*\/|\.[^.]*$/g, '')).html('Add Attributes').appendTo(select);
	$(select).change(function() {
		if ($(this).val() != '') {
			if ($(this).val() == 'addattribute') {
				addFormAttribute($(this).find('option:selected').data('options'));
			}
			else
				insertImage($(this).val());
		}
	});
	
	$('<li/>').append(presentImage)
	.append($('<input/>').attr('type', 'hidden').attr('name','filename[]').val(fileObj.name))
	.append($('<input/>').attr('type', 'hidden').attr('name','img[]').val($.toJSON(images)))
	.append($('<br/>')).append(select).appendTo($('#photos'));
}

/**
 * Insert image to TinyMCE editor at current position
 * @param string url The image url
 */
function insertImage(url) {
	tinyMCE.getInstanceById('content').execCommand('mceInsertContent', false, '<img src="' + url + '" />');
};

function addFormAttribute(fileId)
{
	//console.info(fileId);
	$('#extraattribute').append("<div class='form-group'>"+
	"<div class='col-sm-2'></div>"+	
	"<div class='col-sm-4'>"+
	"<div class='input-group'><span class='input-group-addon'>Attribute</span><input type='text' name='attr_" + fileId + "[]' class='form-control' placeholder='Contoh: Warna'></div>"+
	"</div>"+
	"<div class='col-sm-4'>"+
	"<div class='input-group'><span class='input-group-addon'>Value</span><input type='text' name='attrval_" + fileId + "[]' class='form-control' placeholder='Contoh: Biru'></div>"+
	"</div>"+
	"</div>");
}

/**
 * Init TinyMCE instances
 */
tinyMCE.init({
	theme: 'advanced',
	plugins: 'safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,preelementfix',
	theme_advanced_buttons1: 'bold,italic,underline,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,outdent,indent,ltr,rtl,blockquote,|,forecolor,backcolor,fontselect,fontsizeselect',
	theme_advanced_buttons2: 'link,unlink,table,|,emotions,charmap,image,media,|,code,search,undo,redo,|,preview,fullscreen',
	theme_advanced_buttons3: '',
	theme_advanced_toolbar_location: 'top',
	theme_advanced_toolbar_align: 'left',
	extended_valid_elements: 'font[face|size|color|style],span[id|class|align|style],figure[width|style|class|align|id],figcaption[style|class]',
	width: '480',
	mode: 'textareas',
	elements: 'content',
	content_css: '',
	relative_urls: false,
	remove_script_host: false,
	onchange_callback: function(editor) {
		tinyMCE.triggerSave();
		$('#' + editor.id).valid();
	}
});
<?php endif; ?>




<?php $this->headScript()->captureEnd(); ?>
<?php
/**
 * Put all widget's javascript to the bottom of page 
 */
echo $this->compressor('js', 'bottomBody'); 
?>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-6078961-1', 'auto');
ga('send', 'pageview');
</script>
</body>
</html>