<h4><span class="text-muted">Jual produk anda di madaniyah sekarang.</span></h4>
<span class="help-inline">Masukkan nama toko anda</span>
<form class="form-inline" role="form" method="post" action="<?php echo $this->APP_STATIC_SERVER; ?>/panel/site/add">
	<div class="form-group has-feedback">
		<input type="text" id="name" class="form-control input-lg" name="sitename" autocomplete="off">
		<span class="form-control-feedback" style="width: inherit;right: 5px;font-size: 18px; top: 0 !important;">.madaniyah.com</span>	
	</div>
	<button type="submit" class="btn btn-info btn-lg">Buat Toko</button>
</form>
<div style="padding-bottom:20px"></div>