<?php $this->headTitle('Tag'); ?>
<div class="row">
	<div class="col-md-8">
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->baseUrl(); ?>">Home</a></li>
			<li><a href="<?php echo $this->url([],'tag_tag_list'); ?>">Tag</a></li>
		</ul>
		<h5 class="text-muted"><?php echo $this->helperLoader('news')->dtoday(); ?></h5>
		<?php if ($this->tags->getTotalItemCount() == 0) : ?>
		<p>There is no posts</p>
		<?php else : ?>
		<p><?php echo sprintf('Found %s tags', '<span class="badge">' . $this->tags->getTotalItemCount() . '</span>'); ?></p>
		<div class="panel panel-default">
        	<div class="panel-heading">
        		<h3 class="panel-title">Tags</h3>
	        </div>
	        <div class="panel-body">
	        <?php foreach ($this->tags as $tag) : ?>
	        <?php $l = strtolower(substr($tag->tag_text, 0,1)); ?>
	        
	        	<a href="<?php echo $this->url(['alpha' => $l, 'slug' => $tag->slug_tag_text],'tag_tag_slug'); ?>">#<?php echo $tag->tag_text; ?></a>
	        
	        <?php endforeach; ?>
	        </div>
		</div>
		<div class="text-center">
			<?php echo $this->paginationControl($this->tags,'Sliding','_partial/postpagination.phtml'); ?>
		</div>
		<?php endif; ?>	
	</div>
	<div class="col-md-4">
	
	</div>
</div>