<?php if (isset($this->layout()->allowComment) && $this->username) : ?>
<div id="disqus_thread"></div>
<script>
    var disqus_config = function () {
        this.page.url = '<?php echo $this->APP_URL; ?>';
        this.page.identifier = '<?php echo $this->userAgent()->getServerValue('request_uri'); ?>';
    };
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = '//<?php echo $this->username; ?>.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript><a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
<?php endif; ?>